jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 12.18.2
      - run: node --version
      - run: yarn install
      - run: yarn build
      - run:
          name: Running Server
          command: yarn serve -s build
          background: true
      - run: npm test
orbs:
  node: circleci/node@3.0.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
